

word_100 = [
  "Initiative", "Effectiveness", "Delegation", "Expert", "Delegation", "Tactic", "Proposal", "Selection", "Praise", "Observation",
  "Workload", "Goods", "Replacement", "Matter", "Confirmation", "Figures", "Requirement", "Deadline", "Opportunity", "Objective",
  "Overview", "Attention", "Assumption", "Point", "Survey", "Feature", "Analysis", "Notice", "Assign to", "Maximize",
  "Occupy", "Compare", "Launch", "Implement", "Perceive", "Receive", "Deserve", "Admire", "Pressure", "Expect",
  "Hinder", "Deliver", "Update", "Abandon", "Disapprove", "Send", "Assent", "Estimate", "Assume", "Demand",
  "Specific", "Attend", "Present", "Elaborate", "Require", "Inform", "Reasonable", "Effective", "Face-to-face", "Troublesome",
  "Collaborative", "Groundbreaking", "Uninspired", "Productive", "Faulty", "Final", "Urgent", "Up-to-date", "In particular", "Extra",
  "Formal", "Informal", "Hectic", "Genuine", "Annual", "Essential", "Necessary", "Full-time", "Part-time", "Unique",
  "Accessible", "Flexible", "Properly", "Absolutely", "Unfortunately", "Approximately", "Especially", "Incredibly", "Quarterly", "Monthly",
  "Hourly", "Daily", "Weekly", "Easily", "Effectively", "Strictly", "Professionally", "Significantly", "Gradually", "Sharply"
]

word_300 = [
  "a", "about", "act", "add", "after", "again", "air", "all", "also", "always",
  "animal", "answer", "any", "ask", "at", "back", "base", "be", "before", "begin",
  "big", "book", "both", "boy", "build", "but", "by", "call", "can", "car",
  "care", "carry", "cause", "change", "children", "city", "close", "color", "come", "country",
  "cut", "day", "do", "door", "down", "draw", "each", "earth", "eat", "end",
  "even", "every", "example", "eye", "face", "far", "father", "find", "first", "fish",
  "follow", "food", "for", "friend", "from", "get", "give", "go", "good", "great",
  "group", "grow", "hand", "hard", "have", "he", "head", "hear", "help", "her",
  "here", "high", "home", "house", "how", "idea", "if", "in", "is", "it",
  "just", "keep", "kind", "know", "land", "large", "last", "learn", "letter", "life",
  "light", "like", "little", "live", "long", "look", "low", "make", "man", "many",
  "may", "me", "mean", "men", "might", "money", "more", "most", "mother", "move",
  "much", "must", "my", "name", "near", "need", "never", "new", "next", "night",
  "no", "now", "number", "of", "off", "often", "old", "on", "once", "one",
  "only", "open", "or", "other", "our", "out", "over", "page", "paper", "part",
  "people", "picture", "place", "plant", "play", "point", "put", "read", "real", "right",
  "river", "room", "run", "said", "same", "say", "school", "sea", "second", "see",
  "sentence", "set", "she", "show", "small", "some", "sound", "spell", "stand", "start",
  "still", "study", "such", "take", "tell", "than", "that", "the", "them", "then",
  "there", "these", "they", "thing", "think", "this", "those", "thought", "three", "through",
  "time", "to", "too", "tree", "try", "turn", "two", "under", "until", "up",
  "us", "use", "very", "walk", "want", "watch", "water", "way", "we", "well",
  "went", "were", "what", "when", "where", "which", "while", "who", "why", "will",
  "with", "word", "work", "world", "write", "year", "you", "your"
]

kru_somsri = [
  "abandon", "desert", "ability", "capability", "proficiency", "efficiency", "abnormal", "irregular", "abruptly", "suddenly", 
  "absolutely", "completely", "absurd", "ridiculous", "abundant", "abounding", "accelerate", "expedite", "accept", "admit", 
  "access", "approach", "accommodation", "residence", "accomplish", "succeed", "accumulate", "collect", "accurate", "precise", 
  "accuse", "blame", "achieve", "acknowledge", "acquire", "attain", "activate", "stimulate", "active", "energetic", 
  "dynamic", "adapt", "adjust", "add", "increase", "supplement", "addict", "drunkard", "adolescent", "youngster", 
  "adult", "grown-up", "advantage", "benefit", "advise", "suggest", "recommend", "affair", "business", "affection", 
  "fondness", "affluent", "prosperous", "aggravate", "exasperate", "agriculture", "farming", "aim", "goal", "purpose", 
  "allocate", "distribute", "alternative", "option", "choice", "ambiguous", "vague", "ambition", "inspiration", "analyze", 
  "synthesize", "ancestor", "forefather", "ancient", "archaic", "annoy", "harass", "apparent", "obvious", "application", 
  "appropriate", "suitable", "fitting", "archaeology", "argue", "debate", "dispute", "artificial", "copied", "duplicated", 
  "aspire", "wish", "long for", "assemble", "congregate", "assess", "appraise", "assign", "appoint", "assumption", 
  "presumption", "assure", "ensure", "astronaut", "spaceman", "attach", "join", "enclose", "attention", "heed", 
  "attendance", "presence", "automation", "available", "at hand", "awkward", "inert", "inept", "inapt", "beat", 
  "defeat", "behavior", "conduct", "bereaved", "mourful", "besides", "moreover", "furthermore", "brittle", "fragile", 
  "build", "construct", "establish", "capacity", "category", "classification", "cessation", "stop", "challenge", "defy", 
  "circumstance", "occurrence", "collapse", "relapse", "collide", "clash", "commodity", "merchandise", "communicate", "convey", 
  "companion", "friend", "compare", "correlate", "compensate", "redeem", "competitor", "opposer", "complete", "complex", 
  "complicated", "component", "constituent", "composed of", "constitute", "concentrate", "focus", "conclude", "infer", "condolence", 
  "sympathy", "conference", "convention", "conform", "agree", "confidence", "assurance", "confidential", "secret", "confirm", 
  "affirm", "conscious", "aware", "considerable", "great", "consist of", "constant", "consistent", "contain", "comprise", 
  "consult", "confer", "consumption", "exhaustion", "contaminate", "adulterate", "contradiction", "controversy", "controvert", "contradict", 
  "contend", "convert", "alter", "change", "convince", "persuade", "cooperate", "collaborate", "coordinate", "organize", 
  "counteract", "neutralize", "critical", "vital", "criticism", "comment", "crucial", "essential", "damage", "destruction", 
  "disaster", "dangerous", "hazardous", "deal with", "cope with", "involve", "declare", "announce", "decline", "decrease", 
  "dedicate", "devote", "defend", "protect", "definite", "exact", "destroy", "decay", "demonstrate", "deny", 
  "department", "section", "depend on", "rely on", "depress", "deject", "deprive", "bereave", "detest", "hate", 
  "despise", "detrimental", "perilous", "devastate", "demolish", "devastation", "determine", "device", "tool", "gadget", 
  "devious", "indirect", "diagnosis", "analysis", "die", "expire", "perish", "extinct", "diminutive", "miniature", 
  "disgust", "abhorrence", "disorder", "disorganize", "distinguish", "discriminate", "distract", "deviate", "dominance", "influence", 
  "drought", "shortage", "dwelling", "residence", "ecology", "ecosystem", "effective", "efficient", "effort", "attempt", 
  "elegant", "splendid", "eliminate", "enormous", "colossal", "gigantic", "enthusiastic", "zealous", "entire", "whole", 
  "total", "entrepreneur", "investor", "envious", "jealous", "erase", "delete", "erode", "decompose", "escape", 
  "evade", "elude", "evidence", "proof", "exaggerate", "overstate", "examine", "scrutinize", "excessive", "surplus", 
  "excuse", "explanation", "exhaust", "fatigue", "exhibit", "expose", "existence", "expense", "payment", "explosion", 
  "eruption", "extinguish", "put out", "extreme", "supreme", "utmost", "famine", "starvation", "fascinate", "captivate", 
  "enchant", "fatal", "mortal", "fee", "fare", "flexible", "elastic", "forbid", "prohibit", "restrict", 
  "force", "coerce", "oblige", "foremost", "foundation", "basement", "fruitful", "fertile", "profuse", "function", 
  "duty", "generation", "species", "genetic", "genuine", "authentic", "geology", "get", "gain", "get rid of", 
  "dispose of", "global", "universal", "gloom", "mourning", "gloomy", "grievous", "graceful", "great", "gradually", 
  "little by little", "grief", "affliction", "guarantee", "warrant", "endorse", "habitat", "harvest", "cultivate", 
  "hatch", "brood", "haunting", "unforgettable", "heed", "hibernation", "fast", "ignorant", "negligent", "illegible", 
  "unreadable", "illiterate", "uneducated", "illustration", "floodlight", "illustrate", "elucidate", "illness", "ailment", "inactive", 
  "passive", "incessant", "unceasing", "incidence", "accident", "incredible", "unbelievable", "independent", "self-sufficient", "indicate", 
  "specify", "infant", "newborn", "inferior", "secondary", "inflammation", "ingredient", "element", "inhabit", "reside", 
  "abide", "dwell", "innate", "inborn", "inbred", "intelligent", "intellectual", "initiate", "originate", "inquire", 
  "investigate", "insist on", "persist in", "instantly", "promptly", "installation", "establishment", "instinctive", "intuitive", "integrate", 
  "unite", "unify", "intensity", "concentration", "severity", "invade", "break in", "invalidate", "invalid", "disabled", 
  "investment", "treasure", "ironic", "sarcastic", "jeopardize", "endanger", "justify", "prove", "lantern", "lamp", 
  "legal", "lawful", "legitimate", "literally", "virtually", "long for", "crave for", "yearn", "luxury", "extravagance", 
  "maintenance", "sustenance", "manipulate", "control", "means", "mode", "method", "meteorology", "migrate", "immigrate", 
  "emigrate", "mild", "gentle", "tender", "minute", "miraculous", "marvelous", "miscellaneous", "assorted", "misery", 
  "agony", "mobile", "movable", "moderate", "intermediate", "modify", "mysterious", "puzzling", "neglect", "ignore", 
  "negotiate", "bargain", "nevertheless", "however", "notable", "celebrated", "numerous", "numberless", "nutrition", "nourishment", 
  "nutrient", "oblivious", "unmindful", "observe", "notice", "remark", "observable", "noticeable", "obstacle", "obstruction", 
  "occupy", "engage", "offhand", "accidental", "offspring", "descendant", "old", "antique", "operation", "treatment", 
  "opinion", "attitude", "oppose", "object", "outstanding", "striking", "overcome", "surmount", "rout", "particular", 
  "specific", "pavement", "footpath", "pension", "provident fund", "perceive", "understand", "perform", "act", "periodical", 
  "journal", "permanent", "everlasting", "persuade", "induce", "plan", "policy", "scheme", "please", "delight", 
  "content", "ponder", "reflect", "portrait", "drawing", "possess", "own", "post", "position", "potential", 
  "talent", "practical", "pragmatic", "prevalence", "prevailing", "pervasive", "previous", "foregoing", "primitive", "primary", 
  "priority", "precedence", "proceed", "continue", "progress", "advancement", "proliferate", "spread", "prominent", "eminent", 
  "property", "asset", "proportion", "ratio", "prosperous", "affluent", "provide", "supply", "psychology", "purchase", 
  "buy", "qualification", "feature", "quote", "cite", "rare", "scarce", "rational", "logical", "realistic", 
  "sensible", "recall", "remind", "recover", "recuperate", "refer to", "relate to", "reform", "revolution", "regard", 
  "consider", "regenerate", "reproduce", "relative", "relevant", "release", "liberate", "relieve", "reluctant", "unwilling", 
  "remarkable", "remedy", "therapy", "remote", "distant", "repel", "eject", "replace", "substitute", "reply", 
  "response", "representative", "delegate", "require", "demand", "required", "requisite", "research", "study", "reservoir", 
  "dam", "reserve", "conserve", "preserve", "resolve", "determine", "resort", "lodge", "resource", "riches", 
  "restless", "resume", "curriculum vitae", "restart", "retire", "resign", "reveal", "confess", "sad", "miserable", 
  "seem to", "appear to", "likely to", "self-assured", "self-confident", "self-conscious", "self-esteem", "self-respect", "self-sufficient", "self-sustaining", 
  "justified", "sentimental", "settle down", "locate", "significance", "importance", "skeleton", "skull", "slothful", "sluggish", 
  "so", "thus", "hence", "solution", "answer", "soothe", "alleviate", "sophisticated", "experienced", "sticky", 
  "adhesive", "stop", "quit", "cease", "pause", "strike", "protest", "stubborn", "obstinate", "submit", 
  "succumb", "subscribe", "register", "substance", "matter", "subtract", "deduct", "suburb", "rural", "sufficient", 
  "enough", "adequate", "suffocate", "stifle", "superior", "senior", "supervise", "oversee", "suppress", "oppress", 
  "surplus", "superfluous", "surroundings", "environment", "surveillance", "patrol", "suspect", "doubt", "suspicious", "doubtful", 
  "dubious", "sympathy", "condolence", "symptom", "syndrome", "tactful", "diplomatic", "take over", "inherit", "take part in", 
  "participate in", "tease", "harass", "technique", "device", "temporary", "momentary", "tempt", "allure", "tend to", 
  "trend to", "incline to", "terminal", "final", "terminate", "put an end", "territory", "border", "terror", 
  "horror", "therefore", "thereby", "threaten", "intimidate", "tolerate", "endure", "tough", "enduring", "track", 
  "trail", "hint", "clue", "cue", "tradition", "convention", "tragedy", "suffering", "transfer", "relocate", 
  "transmit", "broadcast", "trial", "experiment", "truly", "actually", "virtually", "ulcer", "eruption", "ultimately", 
  "finally", "undergo", "experience", "unfurnished house", "untidy", "disordered", "up-to-date", "fashionable", "urban", "downtown", 
  "urge", "ask", "request", "urgent", "express", "vacant", "empty", "vague", "obscure", "valid", 
  "reasonable", "variable", "changeable", "various", "assorted", "vending", "selling", "vibration", "quake", "victim", 
  "prey", "vigorous", "forceful", "violence", "severity", "virtue", "integrity", "visible", "apparent", "vital", 
  "crucial", "vulnerable", "weak", "wander", "roam", "ramble", "warn", "caution", "warrant", "guarantee", 
  "endorse", "welfare", "fringe benefit", "win", "vanquish", "wind", "screw", "withdraw", "remove", "wither", 
  "dry", "withhold", "keep back", "witness", "evidence", "withstand", "resist", "worth", "value", "wound", 
  "injury", "zero", "nil"
]